
export enum OpenIdErrorCode {
    REQUEST_UNDEFINED = 'OPENID_REQUEST_UNDEFINED',
    REQUEST_HEADER_UNDEFINED = 'OPENID_REQUEST_HEADER_UNDEFINED',

    TOKEN_STALE = 'OPENID_TOKEN_STALE',
    TOKEN_INVALID = 'OPENID_TOKEN_INVALID',
    TOKEN_EXPIRED = 'OPENID_TOKEN_EXPIRED',
    TOKEN_UNDEFINED = 'TOKEN_UNDEFINED',
    TOKEN_WRONG_ISS = 'OPENID_TOKEN_WRONG_ISS',
    TOKEN_WRONG_TYPE = 'OPENID_TOKEN_WRONG_TYPE',
    TOKEN_WRONG_AUDIENCE = 'OPENID_TOKEN_WRONG_AUDIENCE',
    TOKEN_WRONG_CLIENT_ID = 'OPENID_TOKEN_WRONG_CLIENT_ID',

    TOKEN_ROLE_FORBIDDEN = 'OPENID_TOKEN_ROLE_FORBIDDEN',
    TOKEN_ROLE_INVALID_TYPE = 'OPENID_TOKEN_ROLE_INVALID_TYPE',
    TOKEN_RESOURCE_INVALID = 'OPENID_TOKEN_RESOURCE_INVALID',
    TOKEN_RESOURCE_FORBIDDEN = 'OPENID_TOKEN_RESOURCE_FORBIDDEN',
    TOKEN_RESOURCE_SCOPE_FORBIDDEN = 'OPENID_TOKEN_RESOURCE_SCOPE_FORBIDDEN',

    TOKEN_NOT_ACTIVE = 'OPENID_TOKEN_NOT_ACTIVE',
    TOKEN_NOT_SIGNED = 'OPENID_TOKEN_NOT_SIGNED',
    TOKEN_INVALID_SIGNATURE = 'OPENID_TOKEN_INVALID_SIGNATURE',
}
