
export enum OpenIdErrorCode {
    OPEN_ID_TOKEN_STALE = 'OPEN_ID_TOKEN_STALE',
    OPEN_ID_TOKEN_INVALID = 'OPEN_ID_TOKEN_INVALID',
    OPEN_ID_TOKEN_EXPIRED = 'OPEN_ID_TOKEN_EXPIRED',
    OPEN_ID_TOKEN_UNDEFINED = 'OPEN_TOKEN_UNDEFINED',
    OPEN_ID_TOKEN_WRONG_ISS = 'OPEN_ID_TOKEN_WRONG_ISS',
    OPEN_ID_TOKEN_WRONG_TYPE = 'OPEN_ID_TOKEN_WRONG_TYPE',
    OPEN_ID_TOKEN_WRONG_AUDIENCE = 'OPEN_ID_TOKEN_WRONG_AUDIENCE',
    OPEN_ID_TOKEN_WRONG_CLIENT_ID = 'OPEN_ID_TOKEN_WRONG_CLIENT_ID',

    OPEN_ID_TOKEN_ROLE_FORBIDDEN = 'OPEN_ID_TOKEN_ROLE_FORBIDDEN',
    OPEN_ID_TOKEN_ROLE_INVALID_TYPE = 'OPEN_ID_TOKEN_ROLE_INVALID_TYPE',
    OPEN_ID_TOKEN_RESOURCE_FORBIDDEN = 'OPEN_ID_TOKEN_RESOURCE_FORBIDDEN',
    OPEN_ID_TOKEN_RESOURCE_SCOPE_FORBIDDEN = 'OPEN_ID_TOKEN_RESOURCE_SCOPE_FORBIDDEN',

    OPEN_ID_TOKEN_NOT_ACTIVE = 'OPEN_ID_TOKEN_NOT_ACTIVE',
    OPEN_ID_TOKEN_NOT_SIGNED = 'OPEN_ID_TOKEN_NOT_SIGNED',
    OPEN_ID_TOKEN_SIGNATURE_INVALID = 'OPEN_ID_TOKEN_SIGNATURE_INVALID',
    OPEN_ID_TOKEN_SIGNATURE_ALGORITHM_UNKNOWN = 'TOKEN_SIGNATURE_ALGORITHM_UNKNOWN',

    OPEN_ID_OPTIONS_PUBLIC_KEY_UNDEFINED = 'OPEN_ID_OPTIONS_PUBLIC_KEY_UNDEFINED',

    OPEN_ID_NOT_AUTHORIZED = 'OPEN_ID_NOT_AUTHORIZED',
    OPEN_ID_SESSION_NOT_ACTIVE = 'OPEN_ID_SESSION_NOT_ACTIVE',
}
